# Generated by Django 5.2.5 on 2025-08-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providertimeslot_unique_provider_time_slot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='providertimeslot',
            name='unique_provider_time_slot',
        ),
    ]
