# Generated by Django 5.2.5 on 2025-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_remove_providertimeslot_unique_provider_time_slot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='providertimeslot',
            constraint=models.UniqueConstraint(fields=('provider', 'date', 'start_time', 'end_time'), name='unique_provider_time_slot'),
        ),
    ]
